# Dependabot will run on day 11 of each month at 01:16 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      day: 23
      timezone: "Europe/Berlin"
      cronjob: "16 1 11 * *"
    open-pull-requests-limit: 15
    assignees:
      - "chrmenne"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 23
      timezone: "Europe/Berlin"
      cronjob: "16 1 11 * *"
    open-pull-requests-limit: 15
    assignees:
      - "chrmenne"
